# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Install SSH client
#         run: sudo apt-get install -y openssh-client

#       - name: Add SSH key
#         uses: webfactory/ssh-agent@v0.5.3
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Deploy to Sakura Server
#         run: |
#           rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ bss@bss.sakura.ne.jp:/path/to/remote/directory
